# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: LEAP
title_long: "LEAP: Little Electronic and Arduino Projects"
author: Paul Gallagher
email: gallagher.paul@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  LEAP: Little Electronic and Arduino Projects. my collection of electronics projects, many involving an Arduino in one way or another
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://leap.tardate.com" # the base hostname & protocol for your site, e.g. http://example.com
repo_url: https://github.com/tardate/LittleArduinoProjects
repo_name: LittleArduinoProjects on GitHub

feed_path: "/catalog/atom.xml"

show_social_icons: true

google_analytics: UA-4894631-13

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: tardate

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username:  tardate
bitbucket_username:
stackoverflow_id: 6329
twitter_username: tardate
skype_username:
steam_nickname:
google_plus_id:
linkedin_username: gallagherpaul
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:


# Build settings
markdown: kramdown

highlighter: rouge

# theme: minima
# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - bin
  - wip
  - libraries
  - OSHChip/venv
  - OSHChip/GccToolchain/gcc-arm-none-eabi-5_3-2016q1
  - OSHChip/GccToolchain/_build
  - OSHChip/GccToolchain/sdk.*
  - OSHChip/YottaToolchain/build
  - OSHChip/YottaToolchain/yotta_targets
  - OSHChip/YottaToolchain/yotta_modules

defaults:
  -
    scope:
      path: ""
    values:
      layout: "project"
